version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.9.12-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:6.0.9-alpine
    container_name: 'redis'
    restart: unless-stopped
    ports:
      - "6379:6379"
  postgres:
    image: postgres:13.1-alpine
    container_name: 'postgres'
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      DATABASE_USER: postgres
      DATABASE_DATABASE: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "5432:5432"

